# These are supported funding model platforms

github: [Dhaxor]
# patreon: # your_patreon_username
# open_collective: # your_open_collective_username
# ko_fi: # your_ko_fi_username
# custom: # your_custom_url

